### ISSUE TITLE
Submit failure

### ISSUE THREAD

**Issue by falematte** [louietan/anki-editor#1]
I am running emacs25 on ubuntu 16 LTS, anki 2.032, anki connect is installed and running but every note that I try to submit (even the example) fails. Any tips?

**Comment by louietan** [comment]
Could you provide more information on this? e.g. the decks in you Anki and the Org buffer you were editing.

**Comment by falematte** [comment]
Thank you for the answer. The Org buffer is the one of the example without the Computer/html deck. No error message is given. My anki database consist of 4 old decks already on anki. Let me know if I can help with more informations.

**Comment by louietan** [comment]
Make sure the decks specified in buffer exist in your Anki database.

**Comment by falematte** [comment]
Everything works perfectly, thank you! Is it possible to add an option in the future which create a deck if non existent?

**Comment by louietan** [comment]
There're some improvements to be done and a couple of features to be added, so don't expect it to be considered soon.
Since your issue was resolved, I'm going to close this.
