### ISSUE TITLE
Sorry, the operation was unsuccessful and detailed information is unavailable.

### ISSUE THREAD

**Issue by matthew-piziak** [louietan/anki-editor#10]
Is there a way I can get more information? I have Anki `Version 2.1.0beta29` installed, with AnkiConnect enabled.

Here is the full buffer that fails: https://gist.github.com/matthew-piziak/b96f8ace0c4f367498c7b30c2d256dae

**Comment by matthew-piziak** [comment]
Actually it seems that even the following test file does not work.

```
* Test                                                                 :deck:

** Item :note:
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic (and reversed card)
:ANKI_FAILURE_REASON: Sorry, the operation was unsuccessful and detailed information is unavailable.
:END:
*** Front
Front Test
*** Back
Back Test
```

**Comment by matthew-piziak** [comment]
Hitting `http://localhost:8765/` returns `AnkiConnect v.5`, so I know that it is running.

**Comment by matthew-piziak** [comment]
OS: Arch Linux

Emacs version: `GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.26) of 2018-01-10`

anki-editor version: `20180121.2040` (commit `01776197ec408bf9efe0b2001dfd87dfc16a074d`)

**Comment by matthew-piziak** [comment]
Likewise the example from the `README` does not work:
```
* English                                           :deck:
** Vocabulary
*** Item                                            :note:
    :PROPERTIES:
    :ANKI_NOTE_TYPE: Basic (and reversed card)
    :ANKI_TAGS: vocab idioms
    :END:
**** Front
     (it's) raining cats and dogs
**** Back
     it's raining very hard
```

**Comment by matthew-piziak** [comment]
Let me know if I can provide any additional information.

**Comment by matthew-piziak** [comment]
`anki-editor-export-heading-contents-to-html` works fine. Is there a way to import this HTML into Anki?

**Comment by louietan** [comment]
Possible reasons:
- Deck doesn't exist
- Note is duplicate

This message is shown when anki-connect responds a failure result but without an error message.

**Comment by matthew-piziak** [comment]
It was the first reason! I didn't realize that the deck had to already exist. Could you add a note to that effect in the README? I could make a PR if it would be helpful.

**Comment by louietan** [comment]
OK, go ahead.

**Comment by matthew-piziak** [comment]
@louietan here you go: https://seattle.github.com/louietan/anki-editor/pull/12
