### ISSUE TITLE
Automatic submission of assets

### ISSUE THREAD

**Issue by WielderOfMjolnir** [louietan/anki-editor#11]
From what I understand, it seems like it's possible to submit assets using `anki-connect`, hence it would be pretty neat if assets referenced in org-mode would automatically be submitted to anki upon calling `anki-editor-submit`.

It seems like the following would have to be solved:
- [ ] Transform file path to be compatible with Anki
- [ ] Submit asset (submit note _first_ to stop Anki from treating asset as unsused)

If this is something that would be interesting to include, I might be able to give it a go sometime this week.

**Comment by louietan** [comment]
Sounds good, go ahead and give it a try !

**Comment by louietan** [comment]
Did some work in 9bc11b2979ee335176734e09527afd022bc03208, not fully tested but works for cases I can think of.
