### ISSUE TITLE
Alternative Workflow

### ISSUE THREAD

**Issue by arbox** [louietan/anki-editor#13]
Hi @louietan ,

thank you a lot for this add-on :) It's really useful!

I totally see the point for your proposed workflow.

I'd ask you if my workflow makes sense and you may want to consider it as an option in the future.

I create a lot of notes spread all over different Org files. And I'd like to push them to Anki. So having a note not under a Deck heading but rather to have the Deck as a property of a Note could be a solution for that.
Secondly there is a need for conversion from an ordinary note to an Anki note with respected properties set.
The `note` tag is rather generic and can be used everywhere so probably `:anki-note:` is better in the above case. Additionally setting Anki tags via ordinary tags and not via a property is a way how I'd manage it in an Org document.

What do you think about this workflow? Is it something we can think about and probably implement?

Best,
Andrei

**Comment by louietan** [comment]
Sorry for the very late reply.

As you might know, this package isn't written for handling the use case like in your workflow at first, it's for temporarily editing note with Org buffer in Emacs, in which case the Org file isn't meant to be kept.

Your workflow makes sense to me, as recently I have made lots of notes in different Org files and want to keep them and considering a way to manage them. For the suggestion you gave that putting the deck under the property drawer of note headings, I would like to know how you actually organize notes in a Org file, do you put notes belonging to different decks in the same Org file ? In my case, I'm going to only put notes that belong to the same deck to the same Org file, and add a per-file basis option to indicate in which deck the notes should be created.

As for tags, I don't really want to mess the `note` and `deck` tag that serve special meaning with Anki tags, but Org tags seem to be more flexible than properties when used for searching (I'm gonna to go over the Org manual again to known it better).
Yep, the tag names `note`, `deck` should be more specific, they will be renamed.

**Comment by arbox** [comment]
Hey @louietan 
thank you for your thorough response!
My workflow is a little different since I put all my notes in a date-time tree via a capture template (`journal.org`) so I can have notes for every day, and I can easily filter them by project related tags.
So I'd need the deck property defined per note, not per file.
But still, having a file per deck would be in my opinion an advantage since you can spread notes all over subtrees.
Do you need additional input on that?

**Comment by louietan** [comment]
Both deck per note and deck per file will be supported in the upcoming change, since property values in Org can be retrieved with inheritance.
The change will also support submitting notes with match filter like how it's used in agenda views or sparse trees, along with scope restriction (like region, subtree, buffer, agenda files etc.) benefited from the built-in Org function `org-map-entries`, which will be more flexible I think.

**Comment by arbox** [comment]
That's great news!
Thank you!
