### ISSUE TITLE
Incorrect padding error for known-good image file

### ISSUE THREAD

**Issue by JayDugger** [louietan/anki-editor#15]
I get the error "Submitted 1 notes, with 1 failed. Check property drawers for failure reasons." for the subtree below. The image file (attached) works fine in other Anki notes I've made, and submitting the subtree works if I omit the link. 

```
*** Item                                                               :note:
    :PROPERTIES:
    :ANKI_NOTE_TYPE: jwd - Key sequences - (2015)
    :ANKI_NOTE_ID: 1525220665974
    :ANKI_FAILURE_REASON: Incorrect padding
    :END:

**** Command description
     Give a command name (for the duration of the Emacs session) to the
     most recently defined keyboard macro (‘kmacro-name-last-macro’).

**** Key sequence
     = *C-x C-k n* =

**** Command name
     =(kmacro-name-last-macro)=

**** Program icon
     [[file:/cygdrive/c/Users/owner/AppData/Roaming/Anki2/Knowledge%20Tree/collection.media/240px-EmacsIcon.svg.png][emacs]]
```
![240px-emacsicon svg](https://user-images.githubusercontent.com/33455/39500701-0d0a8438-4d7c-11e8-8fc2-6a1ce51ed82c.png)

**Comment by louietan** [comment]
Sounds like it passes an invalid base64 string for this image to AnkiConnect.

What's the result of the following command from your cygwin terminal ?
```sh
base64 --wrap=0 "/cygdrive/c/Users/owner/AppData/Roaming/Anki2/Knowledge%20Tree/collection.media/240px-EmacsIcon.svg.png"
```
and the result of evaluating the following expression from Emacs ?
```lisp
(shell-command-to-string
                    (format "base64 --wrap=0 %s"
                            (shell-quote-argument "/cygdrive/c/Users/owner/AppData/Roaming/Anki2/Knowledge%20Tree/collection.media/240px-EmacsIcon.svg.png")))
```

**Comment by JayDugger** [comment]
Both of those give the same error: `base64: /cygdrive/c/Users/owner/AppData/Roaming/Anki2/Knowledge%20Tree/collection.media/240px-EmacsIcon.svg.png: No such file or directory`

The same link opens fine from inside org, showing me the correct image in a new buffer, and it also appears if I display images inline.

If I substitute a space for the %20 in either of those commands, then I get the output shown in this [gist](https://gist.github.com/JayDugger/2f27a7018a31b87a08dce818a6495992).

**Comment by louietan** [comment]
Seems shell doesn't recognize url-encoded path and I have to decode the url before passing it to shell.

**Comment by louietan** [comment]
The fix has been pushed, you would get the update from MELPA soon.
