### ISSUE TITLE
  :ANKI_FAILURE_REASON: Error communicating with AnkiConnect using cURL: exited abnormally with code 7

### ISSUE THREAD

**Issue by jpuerj** [louietan/anki-editor#16]
Hello and thank you for this awesome package.

I've been using it for 2 months and it was working great until now. For some reason I can't add any note using the push command. Also, I can't insert note with the interactive command.

I'm using the simpleste example, as provided by the tutorial.

What could be causing this?

**Comment by jpuerj** [comment]
Problem related to the ankiconnect plugin.

**Comment by freckletonj** [comment]
I'm new to the Anki world, so missed some steps that resulted in your same error.

1. install anki : https://apps.ankiweb.net/
2. install an anki plugin : https://ankiweb.net/shared/info/2055492159
3. restart anki

Things seem to work now.
