### ISSUE TITLE
org-use-property-inheritance leads to errors

### ISSUE THREAD

**Issue by 517qf** [louietan/anki-editor#19]
Thanks for your great package!

I think I found an error: If org-use-property-inheritance is set to non-nil it doesn't work as expected: Anki-Editor tries to import too many notes (one for each heading that represents a field) and in the properties for each heading that represents a field I get a property: ":ANKI_FAILURE_REASON: Missing note type".

In retrospect I think I understand why this error occurs ... But it took me some time to figure this out.

Outside of Anki-Editor [property inheritance](https://orgmode.org/manual/Property-inheritance.html) is quite useful for me. So maybe some other people use it too and run into the same problem?

If you can reproduce this you could include a warning in the readme or maybe even anki-editor-setup-minor-mode could set this variable to nil whereas anki-editor-teardown-minor-mode might restore the original value of the variable?

**Comment by louietan** [comment]
Thanks for reporting this bug. This will be fixed by temporarily setting 'org-use-property-inheritance' to nil before iterating note entries.
