### ISSUE TITLE
Duplicated cards

### ISSUE THREAD

**Issue by jwiegley** [louietan/anki-editor#2]
Hi, I was able to get card submitting to work, but although it says "1 card submitted", it adds two cards to the deck:

``` org
* Prayer words                                                                             :deck:

** Vocabulary

*** Item                                                                                   :note:
    :PROPERTIES:
    :ANKI_NOTE_TYPE: Basic (and reversed card)
    :ANKI_TAGS: vocab idioms
    :END:

**** Front

     Hello

**** Back

     World
```

Here is what I see:

<img width="775" alt="screen shot 2018-01-10 at 11 15 45 pm" src="https://user-images.githubusercontent.com/8460/34812820-3b91a664-f65c-11e7-9b37-6232e8c311fe.png">

**Comment by falematte** [comment]
May I ask you which version of emacs/org mode are you using? I am not able to submit ( I get failure even if anki connect is running )

**Comment by louietan** [comment]
Hi, jwiegley. You seems to have misunderstood what is a **card** and what is a **note**.
In Anki and or in Org-mode with this package loaded, you are actually editing **notes**, Anki will automatically create cards for you using the card types of the note type.
In this issue, you specified the "Basic (and reversed card)" note type, which Anki will create two cards for a note, one of the them is Q -> A, the other is A -> Q.

**Comment by jwiegley** [comment]
Ah, thank you, that makes sense!

@falematte I'm using Org-mode 8.2.11 and Emacs 26.0.90 (pretest).
