### ISSUE TITLE
empty drawer gets imported into anki fields

### ISSUE THREAD

**Issue by 517qf** [louietan/anki-editor#20]
if the property drawer is empty like this

```
** Back
:PROPERTIES:
:END:
```

and I push this note into Anki I expected an empty Back field. But in the field Back I get this html source code:

```
<p>
:PROPERTIES:
nil:END:
</p>
```

I think an empty property drawer is unusual but valid according to the org [syntax](https://orgmode.org/manual/Drawers.html)? I think this is an error. Unfortunately I don't know how to change your source code.

I ran into this issue because when I deleted the only property from a drawer but left these opening and closing elements.

Thanks for your time and great software!

**Comment by louietan** [comment]
683c48dfec830ba60bad642621e26eb4d385606d is going to fix this.
