### ISSUE TITLE
Minor misspelling in anki-editor.el at line 550.

### ISSUE THREAD

**Issue by JayDugger** [louietan/anki-editor#25]
[https://github.com/louietan/anki-editor/blob/master/anki-editor.el#L550](url)

```
(define-minor-mode anki-editor-mode
  "anki-eidtor-mode"
  :lighter " anki-editor"
  (if anki-editor-mode (anki-editor-setup-minor-mode)
    (anki-editor-teardown-minor-mode)))
```

Please change "anki-eidtor-mode" to "anki-editor-mode". "eidtor" appears only at that line of the file.

**Comment by louietan** [comment]
Nice catch.
Corrected in latest code.
