### ISSUE TITLE
Create My Own Note Type?

### ISSUE THREAD

**Issue by AloiSama** [louietan/anki-editor#3]
Hello!
Thank you very much for this project, It's been very helpful.
I was wondering what I need to do to use a custom note type with custom fields and such that I created my self. Is it as simple as placing it in the properties tray?

Thank!
AloiSama

**Comment by louietan** [comment]
Yep, just specify the note type in the property drawer and provide fields as subheadings, this package isn't limited to certain note types.
In addition to typing all the stuff manually, it's recommended and more convenient to use the note insertion command `anki-editor-insert-note`, which will guide you to create the skeleton of a note interactively and could reduce the chance of mistyping.

**Comment by AloiSama** [comment]
Perfect, thank you very much! I appreciate your work on this mode :) Helps a lot with my Japanese studies.
