### ISSUE TITLE
Note creation failed for unknown reason for some cards

### ISSUE THREAD

**Issue by Artraxon** [louietan/anki-editor#43]
I've a file with over 40 entries. I can push most of the entries, but some fail for an unknown reason.

Anki is up and running, the deck is set with a file-wide property and most notes are pushed successfully.

Example of successful entry:

** MIMD Strukturen                                                     :MIMD:
*** Shared Memory                                             :Shared_Memory:
**** shared memory, programmiermodell
    :PROPERTIES:
    :ANKI_NOTE_TYPE: SysProg Frage
    :ANKI_NOTE_ID: 1557473650187
    :END:
***** Frage
Was ist bei einer MIMD Architektur mit gemeinsamen Speicher das Programmiermodell?
***** Antwort
Es wird ein globaler Adressraum verwendet
***** Add Reverse

Example entry that I cant push (also child of "MIMD Strukturen")

*** Distributed Memory                                   :Distributed:
**** distributed memory, programmiermodell
    :PROPERTIES:
    :ANKI_NOTE_TYPE: SysProg Frage
    :ANKI_FAILURE_REASON: Note creation failed for unknown reason
    :END:
***** Frage
Was ist bei einer MIMD Architektur mit gemeinsamen Speicher das Programmiermodell?
***** Antwort
Es ist nachrichtenorientiert.
***** Add Reverse

**Comment by louietan** [comment]
Your failed note is considered as duplicate for a previous note has the same content on `Frage`.

See [Anki docs:](https://apps.ankiweb.net/docs/manual.html#adding-cards-and-notes)
> Anki checks the first field for uniqueness, so it will warn you if you enter two cards with a Front field of “apple” (for example).

**Comment by Artraxon** [comment]
oh, i see, thanks. I didn't even notice that ^^
