### ISSUE TITLE
Updating notes fails

### ISSUE THREAD

**Issue by Jumblemuddle** [louietan/anki-editor#45]
I'm unable to create notes and then update them after making changes.
I've created https://github.com/FooSoft/anki-connect/issues/82 to reflect what I believe is the issue, but I wanted to ask here. Is anyone using this successfully? If so, what Anki and AnkiConnect versions are you using?

**Comment by yiufung** [comment]
I installed Anki and anki-editor today. I cannot push the `examples.org` to my Anki. It kept showing `:ANKI_FAILURE_REASON: Note creation failed for unknown reason` in the drawer. 

Using Arch Linux with Version 2.1.11 (3cf770c7), AnkiConnect v.6, Org v9.2.3.

**Comment by yiufung** [comment]
Setting `anki-editor-create-decks` to `t` solves the issue for me.

**Comment by Jumblemuddle** [comment]
It appears the issue I was running into was that I had the note browser open and was expecting to see the change live. This works properly when the note browser is closed.
