### ISSUE TITLE
anki-editor-push-notes fails on new cards

### ISSUE THREAD

**Issue by ppalazon** [louietan/anki-editor#48]
Lastly I have problems creating new cards from anki-editor. The deck is created in Anki, and the sync works perfectly with created cards which has ANKI_NOTE_ID property.

When there are new cards in my org file, I execute anki-editor-push-notes and all notes are sync until the newest card. Then, the new card is created in anki, but the process freezes and stop synchronizing more cards. If I execute again anki-editor-push-notes, all cards are syncronized but the latest card has these property:

:ANKI_FAILURE_REASON: Note creation failed for unknown reason

The card is well created on Anki, but the note_id it's not returned. So, I think that the problem is copying the new note_id

Emacs Version: GNU Emacs 26.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.8) of 2019-04-12
Org: 20190624
Anki-editor: 20190608.1621
Anki: Version 2.1.13 (3ba55990)
AnkiConnect: 2019-06-02

At `request-log` I've found this

[debug] REQUEST
[debug] Run: curl --silent --include --location --compressed --cookie /home/ppalazon/.emacs.d/request/curl-cookie-jar --cookie-jar /home/ppalazon/.emacs.d/request/curl-cookie-jar --write-out \n(:num-redirects %{num_redirects} :url-effective "%{url_effective}") --data-binary @/tmp/emacs-requestuk3b9c --request POST http://127.0.0.1:8765
[debug] REQUEST--CURL-CALLBACK event = finished

[debug] REQUEST--CURL-CALLBACK proc = #<process request curl>
[debug] REQUEST--CURL-CALLBACK buffer = #<buffer  *request curl*>
[debug] REQUEST--CURL-CALLBACK symbol-status = nil
[debug] REQUEST--CALLBACK
[debug] (buffer-string) =
HTTP/1.1 200 OK
Content-Type: text/json
Access-Control-Allow-Origin: *
Content-Length: 33

{"result": [null], "error": null}
[debug] REQUEST-RESPONSE--CANCEL-TIMER
[debug] -CLEAN-HEADER
[debug] -CUT-HEADER
[debug] error-thrown = nil
[debug] -PARSE-DATA
[debug] parser = json-read
[debug] data = ((result nil) (error))
[debug] symbol-status = success
[debug] Executing success callback.
[debug] REQUEST
[debug] Run: curl --silent --include --location --compressed --cookie /home/ppalazon/.emacs.d/request/curl-cookie-jar --cookie-jar /home/ppalazon/.emacs.d/request/curl-cookie-jar --write-out \n(:num-redirects %{num_redirects} :url-effective "%{url_effective}") --data-binary @/tmp/emacs-requestpwrYOV --request POST http://127.0.0.1:8765
[debug] REQUEST--CURL-CALLBACK event = finished

[debug] REQUEST--CURL-CALLBACK proc = #<process request curl>
[debug] REQUEST--CURL-CALLBACK buffer = #<buffer  *request curl*>
[debug] REQUEST--CURL-CALLBACK symbol-status = nil
[debug] REQUEST--CALLBACK
[debug] (buffer-string) =
HTTP/1.1 200 OK
Content-Type: text/json
Access-Control-Allow-Origin: *
Content-Length: 33

{"result": [null], "error": null}
[debug] REQUEST-RESPONSE--CANCEL-TIMER
[debug] -CLEAN-HEADER
[debug] -CUT-HEADER
[debug] error-thrown = nil
[debug] -PARSE-DATA
[debug] parser = json-read
[debug] data = ((result . [nil]) (error))
[debug] symbol-status = success
[debug] Executing success callback.

**Comment by matiya** [comment]
Hi, I have this very same issue.
I have tried both anki 2.1.4 and anki 2.1.13. Emacs 26.2

I also tried downgrading request.el to version 0.3.0 to no avail.

**Comment by matiya** [comment]
Actually, downgrading request.el to https://github.com/tkf/emacs-request/tree/v0.3.0 did solve the problem.

**Comment by dancewhale** [comment]
I have the same issue.

**Comment by hnisonoff** [comment]
@matiya how do you downgrade request? I am unfamiliar with downgrading emacs packages. Thanks!

**Comment by ppalazon** [comment]
It's been solved with latest version of stable emacs (26.3), org-mode and anki-editor. Also I upgrade Anki (2.1.15) and its connector addon. Thank you for your reply @hnisonoff @matiya

**Comment by hnisonoff** [comment]
Thank you for the reply, @ppalazon . I upgraded emacs to 26.3 upgraded to the latest version of org-mode and anki-editor. I am using Anki 2.1.15 and the associated Anki-Connect. It still gives me the same message.
