### ISSUE TITLE
ANKI_FAILURE_REASON: "Symbol’s function definition is void: err"

### ISSUE THREAD

**Issue by hugo-abreu** [louietan/anki-editor#54]
Hello,

When I try to push my notes to anki, it gives me this error: "Symbol’s function definition is void: err". I see it's a definition problem, but I don't understand what "err" corresponds to.

Any help will be appreciated

Best,
Hugo

**Comment by patrick-nicodemus** [comment]
I have the same error. How did you fix this problem?

**Comment by moerrari** [comment]
In my case, revert to [version 0.3.0](https://github.com/louietan/anki-editor/blob/1477ee4b2f29181c60010fc02b629c7457d07a00/anki-editor.el), it was fixed.
