### ISSUE TITLE
org-babel, org-html export and exported figures

### ISSUE THREAD

**Issue by leoc** [louietan/anki-editor#58]
Hoi there!

Thank you for your beautiful package! I was just wondering whether you thought or tried exporting images from code blogs via org-babel?

I often use graphviz code, PlantUML, DITAA or similar. Have you tried these?

For example I try the following org-mode code to generate a graph, but the image is not displayed or pushed to anki.

```
#+BEGIN_SRC dot :file test-dot.png :exports results
graph {
  a -> b
}
#+END_SRC
```

Have you played with that in the past? I will try to investigate a bit later this week, but maybe you have a quick hint. Thanks again!

**Comment by louietan** [comment]
Oops, we introduced a bug when replacing the shell command `sha1sum` with Elisp function, which mistakenly compute the hash against the file name rather than the file content.  I made a patch on develop branch, it should work now.

**Comment by leoc** [comment]
Hah! I looked for the bug but totally overlooked that! Thanks!
