### ISSUE TITLE
Sequence of curly brackets in latex-fragment not compatible with cloze

### ISSUE THREAD

**Issue by WielderOfMjolnir** [louietan/anki-editor#8]
E.g. `\frac{x}{y^{z}}` will fail to compile when wrapped in a cloze for Anki, .e.g. `{{c1::$\frac{x}{y^{z}}$}}`, as it will pre-emptively close the cloze.

I made an attempt at a fix # #9

**Comment by louietan** [comment]
This is the limitation from Anki. For this to work, check out [the Anki manual](https://apps.ankiweb.net/docs/manual.html#latex-conflicts).

**Comment by louietan** [comment]
Added a customization variable to break consecutive braces in latex in 647df92aec8149254857b32b24a9bb09ecedbf50.
